### PR TITLE
Serve Fauxton from relative path.

### PR DESCRIPTION
**Pull request by MichaelJCole**
Hi, this PR takes @thesli's comments and suggestions and packages them into a PR.

You can test this PR like this:

1) Clone couchdb-fauxton
2) `grunt release` to build the changes.
3) put together a test server:

package.json

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.9.8",
    "express-pouchdb": "^0.7.1",
    "morgan": "^1.4.0",
    "pouchdb": "^3.0.6"
  }
}
```

Test.js

```
var express = require('express')
  , app     = express()
  , PouchDB = require('pouchdb')
  , logger  = require('morgan')
  ;

app.use(logger("tiny"));
app.get('/', function(req, res, next) { 
  res.send('Welcome Traveler!  <a href="/express-pouchdb/_utils">Fauxton?</a>');
});
app.use('/custom', require('express-pouchdb')(PouchDB));

app.listen(3000);
```

To run the server with new Fauxton (assuming test and couchdb-fauxton are in same dir)

```
npm install
cd node_modules/express-pouchdb
mv fauxton fauxton.old
ln -s ../../../couchdb-fauxton/dist/release fauxton
node test.js
```

This addresses several issues identified and a couple extra.  From my testing, these issues remain, but none of them are show stoppers.  Compared to not working, 90% working is much better!
- Databases -> Any DB -> Compact & Clean -> Cleanup Views -> "Error: missing" -> POST /custom//newdatabase/_view_cleanup 404
- Databases -> Any DB -> All Design Docs -> Add Doc -> Hmmm... Adds regular doc.
- Create Design Doc through Gear -> New View -> Design Doc Metadata
- Url's have format like: GET /custom//_users -> double // isn't awesome.
- API URL -> wrong url http://localhost:3000/newdatabase2/_all_docs  should include custom path. http://localhost:3000/custom/newdatabase2/_all_docs

### CODE REVIEW

**Comment by nolanlawson** [comment]
I tend to think this is something that should be fixed upstream in Fauxton. This fork should really just be for PouchDB-specific stuff like branding and colors. It would be a shame if Fauxton itself never supported it.

That being said, if it's not high-priority for Fauxton, then I think this is worth merging. @marten-de-vries ?

**Comment by marten-de-vries** [comment]
I would really like our changes to Fauxton to just be theming and a settings file since that would keep upgrading our Fauxton from upstream easier. The current version is quite out of date (e.g. deleting databases is broken IIRC).

If it's impossible to get this into upstream Fauxton though, I'm ok with merging it. The important thing is to move this forward.

**Comment by garth** [comment]
Is there currently a way to get fauxton with pouchdb-express working under `/db` without this patch?

**Comment by marten-de-vries** [comment]
@garth Seems like it's not. (I just gave it a try).

**Comment by garth** [comment]
@marten-de-vries perhaps another option might be to do some route/url rewriting in express so that pouch is always running at the root?

**Comment by marten-de-vries** [comment]
@garth Possible, but this PR is better. Maybe we should just merge it considering no one seems to want to take it upstream.

**Comment by garth** [comment]
@marten-de-vries that would be great. Maybe fauxton could be updated to the latest release at the same time.

**Comment by jvgreenaway** [comment]
This is still a bug in express-pouchdb

**Comment by nolanlawson** [comment]
I think we should work on rebasing on the latest Fauxton since I believe they've fixed this issue upstream.

**Comment by nolanlawson** [comment]
Hi, this repo has been completely rewritten, and the change would now go to http://github.com/apache/couchdb-fauxton . Please file it there if/when you get a chance. :smiley:

**Comment by rjcorwin** [comment]
@nolanlawson This is bummer to not have Fauxton working with the express-pouchdb application servers. Should we file an issue in apache/couchdb-fauxton?  A quick search doesn't pull up anything on folk's needing support for relative paths in fauxton. https://github.com/apache/couchdb-fauxton/search?q=relative+path&type=Issues&utf8=%E2%9C%93

Perhaps it's a non-issue now and we need to get the fauxton code over here? I'm not familiar with how it's all strapped together.

**Pull request closed without merging**
