### PR TITLE
Update fauxton

### PR DESCRIPTION
**Pull request by nolanlawson**
I just bundled all our changes together and rebased on top of the latest master (https://github.com/apache/couchdb-fauxton/commit/eb201de75ebdaa82f096108f5260d2f096064ea1).

Didn't see any merge conflicts that really stood out except for some stuff @nickcolley did in `fauxton.less`. You may want to take a look there to make sure it all looks okay. I tested manually and the interface looks about the same to me; not even sure what was changed.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Ah crap, I just realized all our branding is gone (colors, logo, all that). Yeah, it's going to take some serious effort to get us back up to date.

**Comment by nickcolley** [comment]
I pushed most of the stuff upstream required to update the branding, I think it's probably easier if I just fork the current master/

**Comment by nickcolley** [comment]
@nolanlawson I want to try and get this sorted sooner than later since Hoodie is looking to use pouchdb-server as default.

**Comment by nolanlawson** [comment]
There was a bug in `header.html`; should be fixed now!

**Comment by marten-de-vries** [comment]
This will fix both #7 and #8. But it doesn't yet contain the code of https://github.com/pouchdb/express-pouchdb/pull/242 I presume (considering there's a merge conflict)?

**Comment by marten-de-vries** [comment]
Oh, of course this won't merge, they're based on different code. Forget my comment. #242 looks good so this would probably be ready as well.

**Pull request merged**
